repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$

#  - repo: https://github.com/pycqa/flake8
#    rev: 7.0.0
#    hooks:
#      - id: flake8
#        exclude: '^.*\b(migrations|airbnb_dummy.py|airbnb_sql.py)\b.*$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports,  --config-file=pyproject.toml, --disallow-subclassing-any, --explicit-package-bases]
        additional_dependencies: [django-stubs, pydantic, django-environ]